# Generated by Django 2.2.6 on 2019-10-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pizza_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='toppings',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
