# Generated by Django 2.2.6 on 2019-10-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_topping_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default='pep', max_length=200),
            preserve_default=False,
        ),
    ]
